import os


def generate_report(score, results):
    # build a simple text report
    lines = []
    lines.append("AI RESUME REPORT")
    lines.append("=" * 40)
    lines.append(f"Resume Score: {score}/100")
    lines.append("")
    lines.append("Top Job Matches:")
    lines.append("-" * 40)

    for i, row in results.iterrows():
        lines.append(f"  {row['job title']}  —  Score: {round(row['score'] * 100, 2)}%")

    lines.append("")
    lines.append("Generated by AI Resume Analyzer")

    report_path = "resume_report.txt"

    with open(report_path, "w") as f:
        f.write("\n".join(lines))

    print("Report generated:", report_path)

    return report_path
